version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/OauthService"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/SongService"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/StreamingService"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/FavoritesService"
    schedule:
      interval: "weekly"

