version: '3.8'

services:
  account-service:
    build: ./AccountService
    container_name: account-service
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_TOPIC_NAME: account-topic
    depends_on:
      kafka:
        condition: service_started
      oauth-service:
        condition: service_started

  oauth-service:
    build: ./OauthService
    container_name: oauth-service
    ports:
      - "8082:8082"
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
