apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites-service
  template:
    metadata:
      labels:
        app: favorites-service
    spec:
      containers:
        - name: favorites-service
          image: tpph/favorites-service:0.1
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.default.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://favorites-db.default.svc.cluster.local:5432/favoritesdb
            - name: SPRING_DATASOURCE_USERNAME
              value: favorites_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: favorites_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: https://<your-auth0-domain>/
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCE
              value: <your-api-identifier>
