apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-db
  template:
    metadata:
      labels:
        app: sonar-db
    spec:
      containers:
        - name: sonar-db
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: sonar
            - name: POSTGRES_DB
              value: sonar
            - name: POSTGRES_USER
              value: sonar
